[profile.default]
# auto_detect_solc = true
ffi = true
ast = true
via_ir = false
build_info = true
optimizer = true
optimizer_runs = 200
solc_version = "0.8.24"
evm_version = "berlin"
src = "src"
out = "out"
libs = ["lib"]
scripts = ["script"]
extra_output = ["storageLayout"]
# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
[profile.default.optimizer_details]
constantOptimizer = true
[fmt]
FOUNDRY_FMT_LINE_LENGTH = 100