[profile.default]
auto_detect_solc = true
ffi = true
ast = true
build_info = true
src = "src"
out = "out"
libs = ["lib"]
scripts = ["src/scripts"]
extra_output = ["storageLayout"]
# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
[profile.default.optimizer_details]
constantOptimizer = true
yul = true
[fmt]
FOUNDRY_FMT_LINE_LENGTH = 100